### ISSUE TITLE
Одинарные кавычки в предикатах не работают

### ISSUE THREAD

**Issue by ghost** [ab-5v/jpath#5]
Попытка использовать одинарные кавычки в предикате вызывает ошибку. В yate можно использовать любые. Это специально?

**Comment by ab-5v** [comment]
Да #1 )

Так же можешь обратить внимание [jpath](https://github.com/pasaran/no.jpath) от создателей yate.

**Comment by ghost** [comment]
Ага, так понятнее. Почему-то не заметил #1.

Пасарановский jpath несколько пугает объемом кода.
